using System;
using System.Collections.Generic;
using Newtonsoft.Json;

/// <summary>
/// Data structure for the entire mystery scenario generated by Gemini.
/// </summary>
[Serializable]
public class ScenarioData
{
    public string victim_name;
    public string victim_occupation;
    public string victim_biography;         // NEW: Detailed background to provide player context
    public string victim_discovery_details;
    public string murder_weapon;
    public string murder_location;
    public List<SuspectData> suspects;

    public override string ToString()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}

/// <summary>
/// Data structure for an individual suspect, including their relationship to the victim.
/// </summary>
[Serializable]
public class SuspectData
{
    public string name;
    public string relationship;                   // e.g., "Estranged Daughter", "Personal Chef"
    public string personality;
    public string motive;                         // Only assigned if has_motive is true
    public string access_to_weapon_description;    // The specific "Means" for the Judge to verify
    public string alibi_statement;
    public string minor_secret;                   // Only assigned for the Red Herring

    public Dictionary<string, string> rumors;

    // --- TRIPLE-FILTER LOGIC FLAGS ---
    public bool has_no_alibi;
    public bool has_motive;
    public bool has_access_to_weapon;
    public bool is_killer;

    [JsonIgnore]
    public List<GeminiConnectionManager.GeminiContent> chatHistory = new List<GeminiConnectionManager.GeminiContent>();

    public override string ToString()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}