using System;
using System.Collections.Generic;
using UnityEngine;
using Newtonsoft.Json;

/// <summary>
/// Data structure for the entire mystery scenario generated by Gemini.
/// </summary>
[Serializable]
public class ScenarioData
{
    public string victim_name;
    public string victim_occupation;
    public string victim_biography;         // Detailed background to provide player context
    public string victim_discovery_details;

    [Header("Crime Timeline")]
    public string murder_time;              // e.g., "11:20 PM"
    public string murder_date;              // e.g., "October 12th, 1947"

    [Header("Interrogation Timeline")]
    public string interrogation_date;

    [JsonProperty("murder_weapon")]
    [Header("Crime Details")]
    public string murder_weapon;
    
    [JsonProperty("weapon")]
    private string weapon { set => murder_weapon = value; }

    public string murder_location;
    public List<SuspectData> suspects;

    public override string ToString()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}

/// <summary>
/// Data structure for an individual suspect, including their relationship to the victim and voice settings.
/// </summary>
[Serializable]
public class SuspectData
{
    public string name;
    public string gender;                         // "Male" or "Female"
    public string relationship;                   // e.g., "Estranged Daughter", "Personal Chef"
    public string personality;
    public string voice_id;                       // The Piper Voice Index assigned at generation
    public int model_id;                          // The ID of the visual model (prefab + image)
    public string motive;                         // Only assigned if has_motive is true
    public string access_to_weapon_description;    // The specific "Means" for the Judge to verify
    [JsonProperty("alibi_statement")]
    public string alibi_statement;

    [JsonProperty("alibi")]
    private string alibi { set => alibi_statement = value; }
    public string minor_secret;                   // Only assigned for the Red Herring

    [JsonProperty("rumors")]
    private object rumors_raw
    {
        set
        {
            if (value is string s)
            {
                rumors = new Dictionary<string, string> { { "General", s } };
            }
            else if (value is Newtonsoft.Json.Linq.JObject obj)
            {
                rumors = obj.ToObject<Dictionary<string, string>>();
            }
        }
    }

    [JsonIgnore]
    public Dictionary<string, string> rumors;

    // --- TRIPLE-FILTER LOGIC FLAGS ---
    public bool has_no_alibi;
    public bool has_motive;
    public bool has_access_to_weapon;
    public bool is_killer;

    [JsonIgnore]
    public List<GeminiConnectionManager.GeminiContent> chatHistory = new List<GeminiConnectionManager.GeminiContent>();

    public override string ToString()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}