using System;
using System.Collections.Generic;
using Newtonsoft.Json;

/// <summary>
/// Data structure for the entire mystery scenario generated by Gemini.
/// </summary>
[Serializable]
public class ScenarioData
{
    public string victim_name;
    public string victim_occupation;
    public string victim_discovery_details;
    public string murder_weapon;
    public string murder_location;
    public List<SuspectData> suspects;

    /// <summary>
    /// Pretty-prints the scenario data as JSON for debugging in the Unity console.
    /// </summary>
    public override string ToString()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}

/// <summary>
/// Data structure for an individual suspect, including their memory and logic flags.
/// </summary>
[Serializable]
public class SuspectData
{
    public string name;
    public string personality;
    public string motive;          // Only assigned if has_motive is true
    public string alibi_statement;
    public string minor_secret;    // Only assigned for the Red Herring (has_no_alibi = true, is_killer = false)

    // Key: Suspect Name, Value: Rumor text about that suspect
    public Dictionary<string, string> rumors;

    // --- TRIPLE-FILTER LOGIC FLAGS ---
    public bool has_no_alibi;          // Group A: True if they are lying
    public bool has_motive;            // Group B: True if they have a reason
    public bool has_access_to_weapon;  // Group C: True if they could reach the scene

    public bool is_killer;             // True only if all three flags above are true

    // --- INTERROGATION MEMORY ---
    // Stores the transcript of questions and answers for THIS specific suspect.
    // [JsonIgnore] ensures this local history doesn't interfere with the initial generation.
    [JsonIgnore]
    public List<GeminiConnectionManager.GeminiContent> chatHistory = new List<GeminiConnectionManager.GeminiContent>();

    public override string ToString()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }
}